### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by qwq233** [luern0313/WristBilibili#13]
![IMG_20230915_201433_449](https://github.com/luern0313/WristBilibili/assets/20317838/3b091fa8-af3b-4c16-8939-90811797b8a5)
此处的请求会连带bilibili登入信息一同请求至非bilibili的服务器，能否解释一下这么做的必要性，在我看来这对账号安全确有一定风险。

**Comment by luern0313** [comment]
![image](https://github.com/luern0313/WristBilibili/assets/25398864/c24ad3fd-da79-45d0-a91a-bc3ecd328312)
![image](https://github.com/luern0313/WristBilibili/assets/25398864/182f9e26-8f9c-4312-b2e5-49c711ad8147)
你好！这个接口并没有传入登录cookie，且这个接口已经弃用

**Comment by qwq233** [comment]
哦哦 好的 我看操作bilibili api的都是这个函数所以感觉很奇怪 不好意思了

**Comment by luern0313** [comment]
那就好，刚刚打字手都是抖的，要是有这种失误就只能土下座了

**Comment by luern0313** [comment]
咱肯定不会干这种事...至少不会故意干

**Comment by qwq233** [comment]
https://t.me/TrendingEveryday/15659?single
我主要是看到了这则消息，再加之我个人也是用了蛮久的，因此才起意提取dex看看。
当然了我个人是觉得不太可能说是盗用cookie，我一开始觉得是出于鉴权需求之类的所以需要带登录信息，再加之我之前写玩具模块的时候也检阅过腕上视频的代码，因此也没多大怀疑，不过有人提出我也就以防万一看了下。不过既然问题解决了我也没其他问题了。
麻烦解答了，谢谢。

**Comment by luern0313** [comment]
我去，证明有罪容易，要证明自己无罪就太难了

**Comment by qwq233** [comment]
是的，所以我对这种消息也是慎之又慎，也是自己去查证
