### ISSUE TITLE
关于LICENSE

### ISSUE THREAD

**Issue by 8qewt** [luern0313/WristBilibili#5]
请问一下，我打算使用这个项目的源代码，这个项目打算使用任何的开源协议吗？
如果使用的话，麻烦可以在项目里添加一个LICENSE文件。

**Comment by luern0313** [comment]
你想做什么用呢

**Comment by 8qewt** [comment]
高中党，最近入手了TicWatch，看到大佬你软件想贡献一下，写点新功能，就想fork一份，但是没有LICENSE总感觉有点心里不安

**Comment by luern0313** [comment]
fork或者提pr肯定没关系的

**Comment by 8qewt** [comment]
那就好，主要是想到一般开源软件都会有个许可证，想知道这个软件关于版权是怎么样的

**Comment by W192547975** [comment]
没LICENSE可以fork不能改，约合没开源。参考[许可仓库](https://docs.github.com/zh/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)。
