### ISSUE TITLE
可以用Kotlin吗

### ISSUE THREAD

**Issue by 8qewt** [luern0313/WristBilibili#9]
最近想写写后台下载的Feature，能不能用Kotlin写，不行的话用Java也行。

**Comment by 8qewt** [comment]
Clone下来，现在还不能编译，少了许多东西，望补全，等会提交一个Bugfix，我自己写出来的Bug

**Comment by luern0313** [comment]
我这本地的代码很乱。。还有好多功能还没提交，我可能需要一段时间整理代码。。

**Comment by luern0313** [comment]
后台下载的话我感觉目前用不到吧

**Comment by 8qewt** [comment]
主要是下某些比较大的视频，关闭Activity就会停止下载，还有可能被系统杀掉

**Comment by 8qewt** [comment]
而且用系统通知来展示下载进度也是不错的，有时下一个录播要花上几分钟时间，后台下载还是蛮有用的

**Comment by 8qewt** [comment]
还有一点 自动收回顶栏可以用CoordinatorLayout重写一遍，可以把收回动画做出类似各种手机浏览器的动画一样跟手，哪天我写一个

**Comment by 8qewt** [comment]
![效果](https://user-images.githubusercontent.com/28196049/124359020-b2800f80-dc55-11eb-818d-2d01edec821d.gif)
大概上图这个效果

**Comment by 8qewt** [comment]
顺便再厚颜无耻地问一下，能不能就看我之前写了个主题功能的贡献送我个腕上视频，我没买233，准高三狗手机上没钱😂

**Comment by wenwenwenzq** [comment]
@8qewt 准高三呀，那就别写代码了离2022高考339天没什么时间的了，安心备考吧
后台下载建议用liulishuo的OKdownloader，不过我一次都没成功下载过，可能我的操作问题，后来我换了另一个开源库就解决了

**Comment by 8qewt** [comment]
其实我觉得后台下载要做起来不难，本来就有一个DownloadService，只要用startService让它不随Activity关闭而关闭，下载完毕后stopself就好了，再加个notification就成了

**Comment by 8qewt** [comment]
> @8qewt 准高三呀，那就别写代码了离2022高考339天没什么时间的了，安心备考吧

感谢关心了，写完这个就当我告别之作，高考完再回github撸码

**Comment by wenwenwenzq** [comment]
@8qewt 自己写也可以，不过遇到很多下载的一系列可能没法一时解决，用开源库就能比较快解决

**Comment by wenwenwenzq** [comment]
@8qewt 最后祝你2022高考加油

**Comment by luern0313** [comment]
> 其实我觉得后台下载要做起来不难，本来就有一个DownloadService，只要用startService让它不随Activity关闭而关闭，下载完毕后stopself就好了，再加个notification就成了

对的，我故意做的退出应用关闭service，觉得可能手表系统后台管理比较严格不太好实现就没做

**Comment by luern0313** [comment]
你在qq找我吧

**Comment by 8qewt** [comment]
812558777，谢了

**Comment by 8qewt** [comment]
其实我觉得后台也没那么严格，例如音乐播放器也是前台服务，只要有通知在前台进程被杀的可能性就不太大

**Comment by 8qewt** [comment]
只用过Ticwatch，不知道别的手表杀不杀前台服务

**Comment by luern0313** [comment]
> 只用过Ticwatch，不知道别的手表杀不杀前台服务

ticwear系统好像还算好的了
